### PR TITLE
DRYD-1110: Use aria-labelledby for persistent label on FilterSearchInput

### PR DESCRIPTION
**Pull request by mikejritter**
Resolves: https://collectionspace.atlassian.net/browse/DRYD-1110

### CODE REVIEW

**Review by ray-lee — COMMENTED** [review]
If I'm understanding this right, the label for a search field is the name of the group + the name of the field, e.g. "Identification Department", right? I feel like that misses the most important information, which is that this field is for search. 

I think I'd prefer just wrapping the input in a `<label>`, where the label is just always "Search". Something like:

```
<label>
  <FormattedMessage {...messages.label} />

  <input ... />
</label>
```

(Where `messages.label.defaultMessage` is "Search").

I think that satisfies the requirement. And we wouldn't need the placeholder any more. Having an always-visible label would reduce the size of the search field, but I think that's ok.

**Comment by mikejritter** [comment]
@ray-lee Yea, I had done that initially but didn't really want to change the size of the input box so I went with the `aria-labelledby`. 

I just pushed a change wraps the `<input>` in a `<label>` using what was already defined in the file, and ends up being `Search values`. One thing of note is that it sits on top of the input rather than being aligned horizontally, but I think that's ok. Also let me know if you want it shortened to just `Search` (the placeholder also reads as just `Search` so I was a bit hesitant but it's not a big change either way).

**Comment by ray-lee** [comment]
Let's change it to just "Search", and remove the placeholder, since it is now redundant. Otherwise, I think it looks good.

**Review by ray-lee — APPROVED** [review]
Looks good.

**Pull request merged**
